#GET http://localhost:8080/api/dashboard/summary
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NDU3MTQzLCJleHAiOjE3ODY0NjA3NDN9.5Um71TY93TqD_d9GvvLksJNbrBQ6m9SuHiBlDIee26nnH3LUgFt1fYgnu2_HKp2I

#GET http://localhost:8080/api/dashboard/categories
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NDU3MTQzLCJleHAiOjE3ODY0NjA3NDN9.5Um71TY93TqD_d9GvvLksJNbrBQ6m9SuHiBlDIee26nnH3LUgFt1fYgnu2_HKp2I

GET http://localhost:8080/api/dashboard/monthly
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2NDYyODI2LCJleHAiOjE3ODY0NjY0MjZ9.YcAh0uLJesAT4E-DSpfixXRWGTEbYzWERwTeeyS4VkZ4sTolIdtJr4zKj50gKB4l